collegemanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("college.urls", namespace="college")),
    path('', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('quiz/', include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from .views import CreateQuiz, AddQuestions, QuizList, AttemptQuiz, QuizesList, QuizResults, Result

app_name = "quiz"
urlpatterns = [
    path("create/", CreateQuiz.as_view(), name="createquiz"),
    path("addquestions/", AddQuestions.as_view(), name="addquestions"),
    path("available/", QuizList.as_view(), name="available"),
    path("attempt/<int:id>", AttemptQuiz.as_view(), name="attempt"),
    path("list/", QuizesList.as_view(), name="quizlist"),
    path("results/<int:id>", QuizResults.as_view(), name="results"),
    path("result/<int:id>", Result.as_view(), name="result"),
]

quiz/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.forms import SelectDateWidget
from college.models import Teacher, Student
from django.conf import settings
# Create your models here.

class Quiz(models.Model):
    name = models.CharField(max_length=100)
    duration = models.IntegerField(validators=[MinValueValidator(1, "Duration should be greater than or equal to 1")])
    questions = models.IntegerField(validators=[MinValueValidator(1, "Number of questions should be greater than or equal to 1")])
    author = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    valid_until = models.DateField()

    def __str__(self):
        return self.name
    

class Question(models.Model):
    text = models.TextField()
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    correct = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)


class QuizResult(models.Model):
    quiz = models.ForeignKey("Quiz", on_delete=models.CASCADE)
    student_name = models.ForeignKey(Student, on_delete=models.CASCADE)
    marks = models.IntegerField()
    

quiz/forms.py
from quiz.models import Question, Quiz
from django import forms 

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = "__all__"
    
    def form_valid(self, form):
        print('form_valid called')
        object = form.save(commit=False)
        object.author = self.request.user
        print(object.author)
        object.save()
        return super(self).form_valid(form)
    
    def form_invalid(self, form):
        print("Called me")

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["text", "option1", "option2", "option3", "option4", "correct"]    

quiz/views.py
from datetime import date
from django.shortcuts import redirect, render
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.views import View
from requests import request
from college.models import Student, Teacher
from quiz.forms import QuestionForm, QuizForm
from accounts.views import StudentLoginRequiredMixin, TeacherLoginRequiredMixin
from quiz.models import Question, Quiz, QuizResult
from quiz.helper import quiz_valid
from college.helpers import apology
# Create your views here.
class CreateQuiz(TeacherLoginRequiredMixin, View):
    def get(self, request):
        form = QuizForm()
        content = {
            "form": form,
            "teacher": Teacher.objects.get(username=request.user),
        }
        return render(request, "quiz/options.html", content)

    def post(self, request):
        quizform = QuizForm(request.POST)
        if not quizform.is_valid():
            content = {
                "form": quizform,
            }
            return render(request, "quiz/options.html", content)
        object = quizform.save()
        
        form = QuestionForm()
        context = {
            "number": range(int(request.POST.get("questions"))),
            "count": int(request.POST.get("questions")),
            "duration": request.POST.get("duration"),
            "form": form,
            "quiz": object,
        }
        return render(request, "quiz/questions.html", context)

class AddQuestions(View):
    def get(self, request):
        return redirect(reverse_lazy("quiz:createquiz"))

    def post(self, request):
        count = int(request.POST.get("count"))
        for i in range(count):
            text = request.POST.get("text" + str(i + 1))
            optiona = request.POST.get("optiona" + str(i + 1))
            optionb = request.POST.get("optionb" + str(i + 1))
            optionc = request.POST.get("optionc" + str(i + 1))
            optiond = request.POST.get("optiond" + str(i + 1))
            correctopt = request.POST.get("correct" + str(i + 1))
            correct = request.POST.get(correctopt)
            quiz = Quiz.objects.get(id=int(request.POST.get("quiz")))
            Question.objects.create(text=text, option1=optiona, option2=optionb, option3=optionc, option4=optiond, correct=correct, quiz=quiz)
        return redirect(reverse_lazy("college:teacherview"))

class QuizList(StudentLoginRequiredMixin, ListView):    
    model = Quiz

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["quiz_list"] = context["quiz_list"].filter(valid_until__gte=date.today())
        branch = Student.objects.get(username=self.request.user).branch
        teachers = Teacher.objects.filter(branch = branch)
        context["quiz_list"] = context["quiz_list"].filter(author__in=teachers)
        return context
    
class AttemptQuiz(StudentLoginRequiredMixin, View):
    def get(self, request, id):
        try:
            quiz = Quiz.objects.get(id=id)
        except Exception:
            return apology(request, "Invalid quiz")
        if not quiz_valid(request, id):
            return apology(request, "Invalid quiz")
        questions = Question.objects.filter(quiz=quiz)

        try:
            if QuizResult.objects.get(quiz=quiz, student_name=Student.objects.get(username=request.user)):
                return apology(request, "You already attempted this quiz!")
        except Exception:
            attempted = False
        count = range(len(questions))
        
        context = {
            "questions": zip(questions, count),
            "attempted": attempted,
            "duration": quiz.duration,
        }
        return render(request, "quiz/attempt.html", context)
    
    def post(self, request, id):
        try:
            quiz = Quiz.objects.get(id=id)
        except Exception:
            return apology(request, "Invalid quiz")
        questions = Question.objects.filter(quiz=quiz)
        score = 0
        for i in range(len(questions)):
            correctopt = request.POST.get("correct" + str(i + 1))
            if correctopt == questions[i].correct:
                score += 1
        student = Student.objects.get(username= request.user)
        QuizResult.objects.create(quiz=quiz, student_name=student, marks = score)
        
        return redirect(reverse_lazy("quiz:result", kwargs={"id":id}))

class QuizesList(TeacherLoginRequiredMixin, View):
    def get(self, request):
        try:
            quizes = Quiz.objects.filter(author=Teacher.objects.get(username=request.user))
        except Exception:
            return apology(request, "Quiz does not exist")
        context = {
            "quizes": quizes 
        }
        return render(request, "quiz/quizes_list.html", context)

class QuizResults(TeacherLoginRequiredMixin, View):
    def get(self, request, id):
        
        try:
            quiz = Quiz.objects.get(id=id)
            count = Question.objects.filter(quiz=quiz).count()
            if quiz.author.username != str(request.user):
                return apology(request, "Invalid Quiz")
            results = QuizResult.objects.filter(quiz=quiz)
        except Exception:
            return apology(request, "Invalid Quiz")
        
        context = {
            "results": results,
            "count": count,
        }
        return render(request, "quiz/result_list.html", context)

class Result(StudentLoginRequiredMixin ,View):
    def get(self, request, id):
        try: 
            quiz = Quiz.objects.get(id=id)
            result = QuizResult.objects.get(quiz=quiz, student_name=Student.objects.get(username=request.user))
            count = Question.objects.filter(quiz=quiz).count()
        except Exception:
            return apology(request, "Result Unavailable")
        context = {
            "score": result.marks,
            "total": count,
        }
        return render(request, "quiz/result.html", context)

quiz/templates/quiz/attempt.html
{% extends 'college/layout.html' %}

{% block quiz %}

<div id="timecounter" style="position: absolute; right:2rem; top:6rem; font-size: 20px; font-weight:bold; color: red;">

</div>


<form action="" method="post" style="font-size: 20px;">
    {% csrf_token %}
    {% for question, i in questions %}
    

      <div style="font-weight: bold;" class="mb-3">{{ i|add:1 }}.)&nbsp; {{ question.text|capfirst }} </div>
      <div class="mb-3">
        a.) &nbsp;&nbsp;{{ question.option1|capfirst }} 
        <input type="radio" name="correct{{ i|add:1 }}" value="{{ question.option1 }}" />
      </div>
      <div class="mb-3">
        b.) &nbsp;&nbsp;{{ question.option2|capfirst }} 
        <input type="radio" name="correct{{ i|add:1 }}" value="{{ question.option2 }}" />
      </div>
      <div class="mb-3">
        c.) &nbsp;&nbsp;{{ question.option3|capfirst }} 
        <input type="radio" name="correct{{ i|add:1 }}" value="{{ question.option3 }}" />
      </div>
      <div class="mb-3">
        d.) &nbsp;&nbsp;{{ question.option4|capfirst }} 
        <input type="radio" name="correct{{ i|add:1 }}" value="{{ question.option4 }}" />
      </div>
    <br>
    {% endfor %}
    <input type="submit" value="Submit" />
    <input type="hidden" name="count" value="{{ count }}">
</form>

<script>
  var time = "{{ duration }}" * 60;
var elem = document.getElementById("timecounter");

counter = setInterval(function() {
if(time > 0) {
  minutes = Math.floor((time/60).toFixed(2));
  seconds = time - (minutes * 60)
elem.innerHTML = "Time remaining: "
+ minutes + " min, " + seconds + " sec ";
time--;
} else {
form = document.getElementsByTagName("form")
console.log(form)
clearInterval(counter)
form[0].submit()
}

},1000)
</script>

{% endblock quiz %}

quiz/templates/quiz/options.html
{% extends 'college/layout.html' %}

{% block main %}
    <h2 class="m-5">Create Quiz</h2>
<form action="" method="post">
    {% csrf_token %}
    <div class="mb-3">
        {{ form.name }}
        {{ form.errors.name }}
    </div>
    <div class="mb-3">
        {{ form.duration }}
        {{ form.errors.duration }}
        
    </div>
    <div class="mb-3">
        {{ form.questions }}
        {{ form.errors.questions }}
    </div>
    <div class="mb-3">
        {{ form.valid_until }}
        {{ form.errors.valid_until }}
    </div>
    <input type="hidden" name="author" value="{{ teacher.id }}">
        <button class="btn btn-primary" type="submit">Add Questions</button>
    </form>

    <script>
        let inputs = document.getElementsByTagName("input");
        inputs[1].focus();
        for (let i = 1; i < inputs.length; i++) {
            inputs[i].classList.add("form-control")
            inputs[i].classList.add("mx-auto")
            inputs[i].classList.add("w-auto")
        }
		inputs[1].placeholder = "Name";
		inputs[2].placeholder = "Duration (min)";
		inputs[3].placeholder = "Number of Questions";
		inputs[4].placeholder = "Valid Until(YYYY-MM-DD)";
    </script>
{% endblock main %}

quiz/templates/quiz/questions.html
{% extends 'college/layout.html' %} {% block quiz %}
<div>
  {% for message in messages %}
  <p>{{ message }}</p>
  {% endfor %}

  <form action="{% url 'quiz:addquestions' %}" class="text-left" method="post">
    {% csrf_token %} {% for i in number %}
    <div class="text-left">
      <div style="font-weight: bold; font-size: 1.5rem">
        Question {{ i|add:1}}:
      </div>
    </div>
    <div class="mb-3">{{ form.text }} {{ form.errors.text }}</div>
    <div class="mb-3">
      {{form.option1.label}}: {{ form.option1 }} {{ form.errors.option1 }}
      <input type="radio" name="correct{{ i|add:1 }}" value="optiona{{ i|add:1 }}" required />
    </div>
    <div class="mb-3">
      {{form.option2.label}}: {{ form.option2 }} {{ form.errors.option2 }}
      <input type="radio" name="correct{{ i|add:1 }}" value="optionb{{ i|add:1 }}" required />
    </div>
    <div class="mb-3">
      {{form.option3.label}}: {{ form.option3 }} {{ form.errors.option3 }}
      <input type="radio" name="correct{{ i|add:1 }}" value="optionc{{ i|add:1 }}" required />
    </div>
    <div class="mb-3">
      {{form.option4.label}}: {{ form.option4 }} {{ form.errors.option4 }}
      <input type="radio" name="correct{{ i|add:1 }}" value="optiond{{ i|add:1 }}" required />
    </div>
    {% endfor %}

    <input type="submit" value="Submit" />
    <input type="hidden" name="quiz" value="{{ quiz.id }}" />
    <input type="hidden" name="count" value="{{ count }}" />
  </form>
</div>
<script>
  let inputs = document.getElementsByTagName("input");
        inputs[1].focus();
        for (let i = 1; i < inputs.length; i++) {
            inputs[i].classList.add("w-auto")
        }
  var textarea = document.querySelectorAll("textarea");
  for (let i = 0; i < textarea.length; i++) {
    textarea[i].style.height = "4rem";
    textarea[i].style.width = "40rem";
    textarea[i].name = "text" + (i + 1);
  }
  var option1 = document.getElementsByName("option1");
  var len = option1.length
  for (let i = 0; i < len; i++) {
    option1[0].name = "optiona" + (i + 1);
  }

  var option2 = document.getElementsByName("option2");
  for (let i = 0; i < len; i++) {
    option2[0].name = "optionb" + (i + 1);
  }
  var option3 = document.getElementsByName("option3");
  for (let i = 0; i < len; i++) {
    option3[0].name = "optionc" + (i + 1);
  }
  var option4 = document.getElementsByName("option4");
  for (let i = 0; i < len; i++) {
    option4[0].name = "optiond" + (i + 1);
  }
</script>
{% endblock quiz %}

quiz/templates/quiz/quiz_list.html
{% extends 'college/layout.html' %} {% block quiz %}

<h3 class="m-5">Available Quizes</h3>

<ul class="list-group ">
  {% for quiz in quiz_list %}
  <li class="list-group-item list-group-item-action text-center w-25 center border border-dark">
    <a class="text-decoration-none" style="font-size: 24px; color: black;" href="{% url 'quiz:attempt' quiz.id%}">{{ quiz.name }}</a>
  </li>
  {% endfor %}
</ul>

{% endblock quiz %}

quiz/templates/quiz/quizes_list.html
{% extends 'college/layout.html' %}

{% block title %}Quizes{% endblock title %}

{% block quiz %}
<h2 class="mx-5 text-center">Available Quizes</h2>
<div class="tags m-5">
    <div class="">
      <a style="font-size: 20px; color:blue;" href="{% url 'quiz:createquiz' %}">Create Quiz</a>
    </div>
</div>
{% if quizes %}

<div class="container m-5">
{% for quiz in quizes %}

    <div class="row">
        <div class="w-100 "></div>
        
        <div class="col-6 col-sm-3 border border-dark py-2 text-center" style="font-size: 20px;">{{ quiz.name|capfirst }}
        </div>
        <div class="col-6 col-sm-3 border border-dark py-2 text-center " style="font-size: 20px;"><a class="text-decoration-none" href="{% url 'quiz:results' quiz.id %}">View Results</a></div>
        
    </div>
    
    {% endfor %}
</div>
    {% else %}
    <p style="font-size:30px;" class="mx-5">
        There are no quizes to show!
    </p>
    {% endif %}

<script>
    let anchors = document.querySelectorAll(".tags a")
    console.log(anchors)
    for (let i = 0; i < anchors.length; i++) {
        anchors[i].classList.add("px-2")
        anchors[i].classList.add("text-decoration-none")
        anchors[i].classList.add("border")
        anchors[i].classList.add("rounded")
        anchors[i].classList.add("border-dark")
    }
</script>

{% endblock quiz %}

quiz/templates/quiz/result.html
{% extends 'college/layout.html' %}

{% block title %}
Result
{% endblock title %}


{% block main %}
<h1 class="text-center">Quiz Result</h1>
<div class="m-5" style="font-weight:bold; font-size: 30px; color:red;">
    Your Score: {{ score }} Out Of {{ total }}
</div>
{% endblock main %}

quiz/templates/quiz/result_list.html
{% extends 'college/layout.html' %}

{% block title %}
Results
{% endblock title %}

{% block quiz %}

<h2 class="mx-5 text-center">Quiz Result</h2>
{% if results %}

<div class="container m-5">
    <div class="row">
        <div class="col-6 col-sm-3 border border-dark py-2 text-center " style="font-size: 20px; font-weight:bold;">Student
        </div>
        <div class="col-6 col-sm-3 border border-dark py-2 text-center " style="font-size: 20px; font-weight:bold;">Score</div>
{% for result in results %}

        <div class="w-100 "></div>
        
        <div class="col-6 col-sm-3 border border-dark py-2 text-center" style="font-size: 20px;">{{ result.student_name.username|capfirst }}
        </div>
        <div class="col-6 col-sm-3 border border-dark py-2 text-center " style="font-size: 20px;">{{ result.marks }} / {{ count }}</div>
        
        
        {% endfor %}
    </div>
    </div>
    {% else %}
    <p style="font-size: 30px;" class="text-center my-5">
        No one has attempted the Quiz yet!
    </p>
    {% endif %}

{% endblock quiz %}