accounts/urls.py
from django.urls import path
from .views import RegisterTeacher, TeacherLogin, StudentLogin, RegisterStudent, SuperUserLogin, CreateBranch
app_name = "accounts"

urlpatterns = [
    path("createteacher", RegisterTeacher.as_view(), name="createteacher"),
    path("createstudent", RegisterStudent.as_view(), name="createstudent"),
    path("teacherlogin", TeacherLogin.as_view(), name="loginteacher"),
    path("studentlogin", StudentLogin.as_view(), name="loginstudent"),
    path("adminlogin", SuperUserLogin.as_view(), name="loginadmin"),
    path("createbranch", CreateBranch.as_view(), name="createbranch"),
    
]

college/urls.py
from django.urls import path
from .views import index, AdminView, StudentView, TeacherView, AttendanceView, StudentList, StudentUpdateView, BranchUpdateView, TeacherUpdateView, StudentDeleteView, BranchDeleteView, TeacherDeleteView
app_name = "college"

urlpatterns = [
    path("", index, name="index"),
    path("adminindex", AdminView.as_view(), name="adminview"),
    path("attendance", AttendanceView.as_view(), name="attendance"),
    path("branchdelete", BranchDeleteView.as_view(), name="branchdelete"),
    path("branchupdate/<int:pk>", BranchUpdateView.as_view(), name="branchupdate"),
    path("studentdelete", StudentDeleteView.as_view(), name="studentdelete"),
    path("studentindex/", StudentView.as_view(), name="studentview"),
    path("studentlist", StudentList.as_view(), name="studentlist"),
    path("studentupdate/<int:pk>", StudentUpdateView.as_view(), name="studentupdate"),
    path("teacherdelete", TeacherDeleteView.as_view(), name="teacherdelete"),
    path("teacherindex/", TeacherView.as_view(), name="teacherview"),
    path("teacherupdate/<int:pk>", TeacherUpdateView.as_view(), name="teacherupdate"),
]

collegemanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("college.urls", namespace="college")),
    path('', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('quiz/', include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from .views import CreateQuiz, AddQuestions, QuizList, AttemptQuiz, QuizesList, QuizResults, Result

app_name = "quiz"
urlpatterns = [
    path("create/", CreateQuiz.as_view(), name="createquiz"),
    path("addquestions/", AddQuestions.as_view(), name="addquestions"),
    path("available/", QuizList.as_view(), name="available"),
    path("attempt/<int:id>", AttemptQuiz.as_view(), name="attempt"),
    path("list/", QuizesList.as_view(), name="quizlist"),
    path("results/<int:id>", QuizResults.as_view(), name="results"),
    path("result/<int:id>", Result.as_view(), name="result"),
]

college/models.py
from django.db import models
# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100, null=False)
    prn = models.IntegerField(null=False, unique=True)
    lectures_attended = models.IntegerField(default=0)
    total_lectures = models.IntegerField(default=0)
    branch = models.ForeignKey("Branch", models.CASCADE)
    username = models.CharField(max_length=100, null=False, unique=True)
    email = models.EmailField(null=True)

class Teacher(models.Model):
    name = models.CharField(max_length=100, null=False)
    branch = models.ForeignKey("Branch", on_delete=models.CASCADE, null=False)
    username = models.CharField(max_length=100, null=False, unique=True)
    email = models.EmailField(null=True)

    def __str__(self):
        return self.username

class Branch(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

college/views.py
from .models import Teacher, Student, Branch
from accounts.views import StudentLoginRequiredMixin, SuperUserRequiredMixin, TeacherLoginRequiredMixin
from college.helpers import apology
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView
# Create your views here.
def index(request):
    return render(request, "college/index.html")

class AdminView(SuperUserRequiredMixin, ListView):
    model = Teacher
    template_name = "college/admin_index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student_list = Student.objects.all()
        student_count = Student.objects.all().count()
        teacher_count = Teacher.objects.all().count()
        branch_count = Branch.objects.all().count()
        branches = Branch.objects.all()
        branch_list = []
        for branch in branches:
            st_count = Student.objects.filter(branch = branch).count()
            tc_count = Teacher.objects.filter(branch=branch).count()
            branch_list.append({
                'branch': branch,
                'teacher_count': tc_count,
                'student_count': st_count,
            })
        context["student_list"] = student_list
        context["branch_list"] = branch_list
        context["student_count"] = student_count
        context["teacher_count"] = teacher_count
        context["branch_count"] = branch_count
        return context

class StudentView(StudentLoginRequiredMixin, DetailView):
        
    def get(self, request):
        context = dict()
        context["student"] = Student.objects.get(username = self.request.user) 
        return render(request, "college/student_index.html", context)

class TeacherView(TeacherLoginRequiredMixin, DetailView):
    def get(self, request):
        context = dict()
        context["teacher"] = Teacher.objects.get(username = self.request.user) 
        return render(request, "college/teacher_index.html", context)
    
class AttendanceView(TeacherLoginRequiredMixin, View):
    def get(self, request):
        branch = (Teacher.objects.values("branch").get(username = request.user))["branch"]
        student_list = Student.objects.filter(branch= branch)
        context = {
            "student_list": student_list,
            'pk': Teacher.objects.values('id').get(username = request.user)['id'],
        }
        return render(request, "college/attendance.html", context)
    def post(self, request):
        branch = (Teacher.objects.values("branch").get(username = request.user))["branch"]
        student_list = Student.objects.filter(branch= branch)
        for student in student_list:
            was_present = request.POST.get(student.name)
            if was_present == "yes":
                student.lectures_attended += 1
            student.total_lectures += 1
            student.save()
        return redirect(reverse_lazy("college:teacherview"))

class StudentList(TeacherLoginRequiredMixin, ListView):
    model = Student
    template_name = "college/student_list.html"
    
    def get_queryset(self):
        branch = (Teacher.objects.values("branch").get(username = self.request.user))["branch"]
        return super().get_queryset().filter(branch = branch)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class StudentUpdateView(SuperUserRequiredMixin, UpdateView):
    model = Student
    template_name = "college/student_update_form.html"    
    success_url = reverse_lazy("college:adminview")
    fields = ["name", "prn", "branch", "email"]

class TeacherUpdateView(SuperUserRequiredMixin, UpdateView):
    model = Teacher
    template_name = "college/teacher_update_form.html"    
    success_url = reverse_lazy("college:adminview")
    fields = ["name", "branch", "email"]

class BranchUpdateView(SuperUserRequiredMixin, UpdateView):
    model = Branch
    template_name = "college/branch_update_form.html"    
    success_url = reverse_lazy("college:adminview")
    fields = ["name"]

class StudentDeleteView(SuperUserRequiredMixin, View):
    def get(self, request):
        return redirect(reverse_lazy("college:adminview"))
    
    def post(self, request):
        student_id = request.POST.get("id")
        try: 
            student = Student.objects.get(id = student_id)
            username = student.username
            user = User.objects.get(username=username)
            student.delete()
            user.delete()
        except:
            return apology("Student Not Found!")
        return redirect(reverse_lazy("college:adminview"))
class TeacherDeleteView(SuperUserRequiredMixin, View):
    def get(self, request):
        return redirect(reverse_lazy("college:adminview"))
    
    def post(self, request):
        teacher_id = request.POST.get("id")
        try: 
            teacher = Teacher.objects.get(id = teacher_id)
            username = teacher.username
            user = User.objects.get(username=username)
            teacher.delete()
            user.delete() 
        except:
            return apology("Student Not Found!")
        return redirect(reverse_lazy("college:adminview"))


class BranchDeleteView(SuperUserRequiredMixin, View):
    def get(self, request):
        return redirect(reverse_lazy("college:adminview"))
    
    def post(self, request):
        branch_id = request.POST.get("id")
        try: 
            branch = Branch.objects.get(id = branch_id)
            branch.delete() 
        except:
            return apology("Branch Not Found!")
        return redirect(reverse_lazy("college:adminview"))

college/templates/college/admin_index.html
{% extends "college/layout.html" %} {% block title %}Admin {% endblock %} 
{% load operations %} {% block main %}
<style>
  table a {
    background-color: rgb(239, 239, 239);
  }
  table a:hover,
  .hovered:hover {
    background-color: rgb(229, 229, 229);
  }
</style>
<h2>Teachers</h2>
<table class="table tablestriped">
  <thead>
    <tr>
      <th class="text-start">Name</th>
      <th class="text-start">UserName</th>
      <th class="text-start">Email</th>
      <th class="text-end">Branch</th>
    </tr>
  </thead>
  <tbody>
    {% for teacher in object_list %}
    <tr>
      <td class="text-start">{{ teacher.name }}</td>
      <td class="text-start">{{ teacher.username }}</td>
      <td class="text-start">{{ teacher.email }}</td>
      <td class="text-end">{{ teacher.branch }}</td>
      <td class="text-end">
        <a href="{% url 'college:teacherupdate' teacher.id %}">Update</a>
        <form
          action="{% url 'college:teacherdelete' %}"
          method="post"
          style="display: inline"
        >
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ teacher.id }}" />
          <input type="submit" value="Delete" />
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td class="border-0 fw-bold text-end" colspan="4">Teacher Count:</td>
      <td class="border-0 text-start">{{ teacher_count }}</td>
    </tr>
  </tfoot>
</table>
<h2>Students</h2>
<table class="table tablestriped">
  <thead>
    <tr>
      <th class="text-start">Name</th>
      <th class="text-start">UserName</th>
      <th class="text-start">Email</th>
      <th class="text-start">Prn</th>
      <th class="text-end">Branch</th>
      <th class="text-end">Attendance</th>
    </tr>
  </thead>
  <tbody> 
    {% if student_list %}
    {% for student in student_list %}
    <tr>
      <td class="text-start">{{ student.name }}</td>
      <td class="text-start">{{ student.username }}</td>
      <td class="text-start">{{ student.email }}</td>
      <td class="text-start">{{ student.prn }}</td>
      <td class="text-end">{{ student.branch }}</td>
      <td class="text-end">
        {{ student.lectures_attended|divide:student.total_lectures }}
      </td>
      <td class="text-end">
        <a href="{% url 'college:studentupdate' student.id %}">Update</a>
        <form
        action="{% url 'college:studentdelete' %}"
        method="post"
        style="display: inline"
        >
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ student.id }}" />
        <input type="submit" value="Delete" />
      </form>
    </td>
  </tr>
  {% endfor %}
  {% endif %}
  </tbody>
  <tfoot>
    <tr>
      <td class="border-0 fw-bold text-end" colspan="6">Student Count:</td>
      <td class="border-0 text-start">{{ student_count }}</td>
    </tr>
  </tfoot>
</table>
<h2>Branches</h2>
<table class="table tablestriped">
  <thead>
    <tr>
      <th class="text-start">Name</th>
      <th class="text-start">Students</th>
      <th class="text-end">Teachers</th>
    </tr>
  </thead>
  <tbody>
    {% for branch in branch_list %}
    <tr>
      <td class="text-start">{{ branch.branch.name }}</td>
      <td class="text-start">{{ branch.student_count }}</td>
      <td class="text-end">{{ branch.teacher_count }}</td>
      <td class="text-end">
        <a href="{% url 'college:branchupdate' branch.branch.id %}">Update</a>
        <form
          action="{% url 'college:branchdelete' %}"
          method="post"
          style="display: inline"
        >
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ branch.branch.id }}" />
          <input type="submit" value="Delete" />
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td class="border-0 fw-bold text-end" colspan="4">Branch Count:</td>
      <td class="border-0 text-start">{{ branch_count }}</td>
    </tr>
  </tfoot>
</table>
<script>
  let anchors = document.querySelectorAll("table a");
  for (let i = 0; i < anchors.length; i++) {
    anchors[i].classList.add("px-2");
    anchors[i].classList.add("text-decoration-none");
    anchors[i].classList.add("text-decoration-none");
    anchors[i].classList.add("text-dark");
    anchors[i].classList.add("border");
    anchors[i].classList.add("rounded");
    anchors[i].classList.add("border-dark");
  }
  let submits = document.querySelectorAll("input");
  for (let i = 0; i < submits.length; i++) {
    if (submits[i].type == "submit") {
      submits[i].classList.add("hovered");
      submits[i].classList.add("rounded");
      submits[i].classList.add("border");
      submits[i].classList.add("border-dark");
    }
  }
</script>
{% endblock %}

college/templates/college/apology.html
{% extends "college/layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <!-- https://memegen.link/ -->
    <img alt="{{ top }}" class="border img-fluid" src="http://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
{% endblock %}

college/templates/college/attendance.html
{% extends "college/layout.html" %}
{% block title %}Attendance{% endblock %}
{% load operations %}
{% block main %}
<h2>Students</h2>
<form action="" method="post">
    {% csrf_token %}
    <table class="table tablestriped">
        <thead>
            <tr>
                <th class="text-start">Name</th>
                <th class="text-start">Attendance</th>
            </tr>
        </thead>
        <tbody>
            {% for student in student_list %}
            <tr>
                <td class="text-start">{{ student.name }}</td>
                <td class="text-start"> <input type="checkbox" name="{{ student.name }}" value="yes" id="" checked> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button id="submit" type="submit">Submit</button>
    <button id="cancel" type="cancel" onclick="cancelthis();">Cancel</button>
</form>



<script>
    var positive = true;
    var link = "{% url 'college:teacherview' %}";
    function cancelthis() {
        positive = false;
        window.location = link;
    }
    document.querySelector("form").addEventListener("submit", function(e) {
        if (positive == false) {
            e.preventDefault()
        }
    });
    
</script>
{% endblock %}

college/templates/college/branch_form.html
{% extends "college/layout.html" %}
{% block title %}Register{% endblock %}
{% block main %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.name }}
            {{ form.errors.name }}
        </div>
            {% comment %} {{ form.errors|typededo }} {% endcomment %}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <script>
        let inputs = document.getElementsByTagName("input");
        inputs[1].focus();
        for (let i = 1; i < inputs.length; i++) {
            inputs[i].classList.add("form-control")
            inputs[i].classList.add("mx-auto")
            inputs[i].classList.add("w-auto")
        }
		inputs[1].placeholder = "Branch Name";
        </script> 
       
    {% endblock %}

college/templates/college/branch_update_form.html
{% extends "college/layout.html" %}
{% block title %}Update Branch{% endblock %}
{% block main %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.name }}
            {{ form.errors.name }}
        </div>
            {% comment %} {{ form.errors|typededo }} {% endcomment %}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
        <script>
        let inputs = document.getElementsByTagName("input");
        inputs[1].focus();
        for (let i = 1; i < inputs.length; i++) {
            inputs[i].classList.add("form-control")
            inputs[i].classList.add("mx-auto")
            inputs[i].classList.add("w-auto")
        }
		
		inputs[1].placeholder = "Name";
        </script> 
       
    {% endblock %}

college/templates/college/index.html
{% extends 'college/layout.html' %}
{% block title %}
Home
{% endblock title %}

{% block main %}

<style>
    
  .hero_section{
    min-height: 90vh;
    background: linear-gradient( rgba(11, 7, 7, 0.679),
    rgba(29, 20, 20, 0.527)),
    url("../../static/college/clg.jpg");
    background-position: center;
    background-size: cover;
    background-clip: border-box;
    background-origin: border-box; 
    background-attachment: fixed;
    padding: 3.5rem 1rem;
    font-family: 'Montserrat Alternates', sans-serif;
    font-weight: 800;
    color: aliceblue;
  }
</style>
  <div class="jumbotron hero_section">
      <h1 class="display-2 bold py-5">AKT College Manager</h1>
      <p class="display-6 lead bold">Safely record and track your classroom activities</p>
      <hr class="display-6 my-4 bold">
      <p>Have a query or need any help? Call the button below.</p>
      <p class="lead">
      <span class="btn btn-primary btn rounded">Call Now</span>
      </p>
  </div>
  
  <ul class="list-group py-5">
    <li class="list-group-item active" aria-current="true">Notice and Updates</li>
    <li class="list-group-item">Orientation for new students on 10 August! Help as organize an event as volunteers.</li>
    <li class="list-group-item">Join the free workshop on meditation next Saturday at 4pm conducted by one of our graduates.</li>
    <li class="list-group-item">To discontinue any units, please unenroll by 5 August.[2nd Semseter Students]</li>
    <li class="list-group-item">College Library to remain closed next Sunday.</li>
    <span class="text-info bg-dark">Previous Notices</span>
  </ul>
{% endblock main %}

college/templates/college/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1, width=device-width">
        <!-- http://getbootstrap.com/docs/5.1/ -->
        <link crossorigin="anonymous"
              href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              rel="stylesheet">
        <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"></script>
        <!-- https://favicon.io/emoji-favicons/money-bag/ -->
        {% load static %}
        {% comment %} <link href="{% static 'home/favicon.ico' %}" rel="icon"> {% endcomment %}
        {% load static %}
        <link href="{% static 'college/styles.css' %}" rel="stylesheet">
        <title>AKT:
            {% block title %}{% endblock %}
        </title>
        <style>

            #logo_header{
                display: block;
                width: 80px;
                height: 50px;
                box-sizing: padding-box;
                border: 2px solid rgba(0, 0, 0, 0.904);
                filter: invert(1);
            }

        </style>
    </head>
    <body>
         <nav class="bg-dark border navbar navbar-expand-md navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="../../static/college/bg_logo.png" alt="logo" id="logo_header">
                </a>
                <button aria-controls="navbar"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                        class="navbar-toggler"
                        data-bs-target="#navbar"
                        data-bs-toggle="collapse"
                        type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar">
                    {% if user.is_superuser %}
                        <ul class="navbar-nav me-auto mt-2">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'college:adminview' %}">Index</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:createstudent' %}">Create Student</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:createteacher' %}">Create Teacher</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:createbranch' %}">Create Branch</a>
                            </li>
                        </ul>
                    {% endif %}
                    
                    
                    {% if user.is_authenticated %}
                    
                    {% load check %}

                    {% if user|isStudent %}
                    <ul class="navbar-nav me-auto mt-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'college:studentview' %}">Index</a>
                        </li>
                    </ul>
                    {% endif %}
                    {% if user|isTeacher %}
                    <ul class="navbar-nav me-auto mt-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'college:teacherview' %}">Index</a>
                        </li>
                    </ul>
                    {% endif %}
                        
                    <ul class="navbar-nav ms-auto mt-2">

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}?next={% url 'college:index' %}">Log Out</a>
                        </li>
                    </ul>

                    {% else %}
                    
                        <ul class="navbar-nav ms-auto mt-2">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:loginstudent' %}">Student Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:loginteacher' %}">Teacher Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:loginadmin' %}">Admin Login</a>
                            </li>
                        </ul> 

                    {% endif %}
                        
                </div>
            </div>
        </nav>
        {% if messages %}
            {% for message in messages %}
                <header>
                    <div class="text-center alert alert-{{ message.tags }} mb-0">{{ message|safe }}</div>
                </header>
            {% endfor %}
        {% endif %} 
            
            <main class="container py-5">
                {% block quiz %}
                <div class="text-center">
                    {% block main %}{% endblock main%}
                </div>
                {% endblock quiz %}
            </main>
                       
    </body>
</html>

college/templates/college/student_form.html
{% extends "college/layout.html" %}
{% block title %}Register{% endblock %}
{% block main %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.username }}
            {{ form.errors.username }}
        </div>
        <div class="mb-3">
            {{ form.name }}
            {{ form.errors.name }}
        </div>
        <div class="mb-3">
            {{ form.email }}
            {{ form.errors.email }}
        </div>
        <div class="mb-3">
            {{ form.prn }}
            {{ form.errors.prn }}
        </div>
        
            <div class="mb-3 ">
                {{ form.password }}
                {{ form.errors.password }}
            </div>
            <div class="mb-3 ">
                {{ form.branch }}
                {{ form.errors.branch }}
            </div> 
            {% comment %} {{ form.errors|typededo }} {% endcomment %}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <script>
        let inputs = document.getElementsByTagName("input");
        inputs[1].focus();
        for (let i = 1; i < inputs.length; i++) {
            inputs[i].classList.add("form-control")
            inputs[i].classList.add("mx-auto")
            inputs[i].classList.add("w-auto")
        }
		inputs[1].placeholder = "Username";
		inputs[2].placeholder = "Name";
		inputs[3].placeholder = "Email";
		inputs[4].placeholder = "Prn";
		inputs[5].placeholder = "Password";
        let select1 = document.getElementsByTagName("select");
        let option1 = document.createElement("option");
        var t = document.createTextNode("Branch");
        option1.appendChild(t);
        option1.defaultSelected = true;
        option1.disabled = true;
        select1[0].appendChild(option1);
        </script> 
       
    {% endblock %}

college/templates/college/student_index.html
{% extends "college/layout.html" %}
{% block title %}Student Detail{% endblock %}
{% load operations %}
{% block main %}

  <h2>Student Detail</h2>
  <table class="table table-bordered border-dark">
        <tr>
          <th>Name</th>
          <td>{{ student.name }}</td>
        </tr>
        <tr>
          <th>UserName</th>
          <td>{{ student.username }}</td>
        </tr>
        <tr>
          <th>Email</th>
          <td>{{ student.email }}</td>
        </tr>
        <tr>
          <th>PRN</th>
          <td>{{ student.prn }}</td>
        </tr>
        <tr>
          <th>Attendance</th>
          <td>{{ student.lectures_attended|divide:student.total_lectures }}</td>
        </tr>
        <tr>
          <th>Branch</th>
          <td>{{ student.branch }}</td>
        </tr>
      </table>
      <div class="tags my-5">
        <div class="">
          <a href="{% url 'quiz:available' %}">Take Quizes</a>
        </div>
        <script>
          let anchors = document.querySelectorAll(".tags a")
          console.log(anchors)
          for (let i = 0; i < anchors.length; i++) {
              anchors[i].classList.add("px-2")
              anchors[i].classList.add("text-decoration-none")
              anchors[i].classList.add("text-decoration-none")
              anchors[i].classList.add("text-dark")
              anchors[i].classList.add("border")
              anchors[i].classList.add("rounded")
              anchors[i].classList.add("border-dark")
          }
      </script>
{% endblock %}

college/templates/college/student_list.html
{% extends "college/layout.html" %}
{% block title %}Admin{% endblock %}
{% load operations %}
{% block main %}

<h2>Students</h2>
<table class="table tablestriped">
    <thead>
        <tr>
            <th class="text-start">Name</th>
            <th class="text-start">UserName</th>
            <th class="text-start">Prn</th>
            <th class="text-end">Branch</th>
            <th class="text-end">Attendance</th>
        </tr>
    </thead>
    <tbody>
        {% for student in student_list %}
        <tr>
            <td class="text-start">{{ student.name }}</td>
            <td class="text-start">{{ student.username }}</td>
            <td class="text-start">{{ student.prn }}</td>
            <td class="text-end">{{ student.branch }}</td>
            <td class="text-end"> {{ student.lectures_attended|divide:student.total_lectures }} </td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td class="border-0 fw-bold text-end" colspan="5">Student Count:</td>
                <td class="border-0 ">{{ student_list|length }}</td>
            </tr>
        </tfoot>
    </table>
{% endblock %}

college/templates/college/teacher_index.html
{% extends "college/layout.html" %}
{% block title %}Teacher Detail{% endblock %}
{% load operations %}
{% block main %}
<h2>Teacher Detail</h2>
<table class="table table-bordered border-dark">
    <tr>
      <th>Name</th>
      <td>{{ teacher.name }}</td>
    </tr>
    <tr>
      <th>UserName</th>
      <td>{{ teacher.username }}</td>
    </tr>
    <tr>
      <th>Email</th>
      <td>{{ teacher.email }}</td>
    </tr>
    <tr>
      <th>Branch</th>
      <td>{{ teacher.branch }}</td>
    </tr>
  </table>
  <style>
    .tags a {
        background-color: rgb(239, 239, 239);
    }
    .tags a:hover {
        background-color: rgb(229, 229, 229);
    }
    
  </style>
  <div class="tags my-5">
    <div class="">
      <a href="{% url 'college:attendance' %}">Take Attendance</a>
    </div>
    <div class="my-3">
      <a href="{% url 'college:studentlist' %}">View Students</a>
    </div>
    <div class="my-3">
      <a href="{% url 'quiz:quizlist' %}">Show Quizes</a>
    </div>
    </div>
    <script>
        let anchors = document.querySelectorAll(".tags a")
        console.log(anchors)
        for (let i = 0; i < anchors.length; i++) {
            anchors[i].classList.add("px-2")
            anchors[i].classList.add("text-decoration-none")
            anchors[i].classList.add("text-decoration-none")
            anchors[i].classList.add("text-dark")
            anchors[i].classList.add("border")
            anchors[i].classList.add("rounded")
            anchors[i].classList.add("border-dark")
        }
    </script>
{% endblock %}